-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJVpnKygnOj+DOHL6
HkXYgUgdBdyobgC6P6/EGmmqrBSgCgYIKoZIzj0DAQehRANCAATDGmiSQzfS9Kvw
Vr5xp1ANlXx/O4+DStcZ/I79O9RtxG16oemrjO+itnU3kjj1hDxd8MWwkugnQqrN
qv0cPHUS
-----END PRIVATE KEY-----